spring.application.name=final_project

## 모든 설정파일을 이 곳에 넣는다.
# DB connection(Oracle) - spring(context.xml)
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=springboot_ict04
spring.datasource.password=tiger

# http port number(default 8080)
server.port=8081

## MyBatis - spring(dataSource-config.xml)
#mybatis.mapper-locations=mappers/**/*.xml
## 카멜 케이스. false를 주면 강제변환(bNum -> b_num)을 막는다.
#mybatis.configuration.map-underscore-to-camel-case=false
#logging.level.com.atoz_develop.mybatissample.repository=TRACE

# JPA SQL SHOW -> 있으면 편함
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
# spring.jpa.show-sql=true : 에러가 났을때 console 창에 어떤 sql이 오류 났는지 띄워줌

# custom error page
server.error.whitelabel.enabled=false