#spring.application.name=final_project
#
## http port number(default 8080)
#server.port=8081
#
## MyBatis - spring(dataSource-config.xml)
#mybatis.mapper-locations=mappers/**/*.xml
## \uCE74\uBA5C \uCF00\uC774\uC2A4. false\uB97C \uC8FC\uBA74 \uAC15\uC81C\uBCC0\uD658(bNum -> b_num)\uC744 \uB9C9\uB294\uB2E4.
#mybatis.configuration.map-underscore-to-camel-case=false
#logging.level.com.atoz_develop.mybatissample.repository=TRACE
#
## JPA SQL SHOW -> 있으면 편함
##spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
#spring.jpa.show-sql=true
## spring.jpa.show-sql=true : 에러가 났을때 console 창에 어떤 sql이 오류 났는지 띄워줌
#
## custom error page
#server.error.whitelabel.enabled=false
#
## db 등 숨길 정보들을 담은 파일 연결
## application-이름.properties으로 나눈 파일 연결 -> spring.profiles.include=이름
#spring.profiles.include=db
#spring.profiles.active=db
### ↳ 프로파일 활성화